mission-apprentissage/sirius

server/src/common/emails/finAnnee.mjml.ejs
correction et ajout mentions légales
=> mentions légales

server/package.json, server/src/campagnes/campagnesHttp.js, server/src/campagnes/validators.js, server/src/components.js, server/src/core/campagnes.js, server/src/core/errors.js, server/src/core/http/httpServer.js, server/src/core/http/validatorMiddleware.js, server/test/integration/campagnes/createCampagne.test.js, server/test/integration/campagnes/deleteCampagne.test.js, server/test/integration/campagnes/getAllCampagnes.test.js, server/test/integration/campagnes/getOneCampagne.test.js, server/test/integration/utils/fixtures.js, server/yarn.lock
This PR adds `GET, POST, DELETE` routes, related validators, controllers, error handling, fixture and test.
Not perfect as we're still in the POC stage.
=> [Server] Add `campagnes` domain

.github/workflows/ci.yml
This PR upgrade node version in CI to match the projects versions.
=> [CI] Upgrade node version in GH CI

server/package.json, server/src/campagnes/campagnesHttp.js, server/src/components.js, server/src/core/campagnes.js, server/src/core/connectToMongoDB.js, server/src/core/logger.js, server/src/core/temoignages.js, server/src/models/campagne.js, server/src/models/log.js, server/src/models/temoignage.js, server/src/temoignages/temoignagesHttp.js, server/test/integration/campagnes/createCampagne.test.js, server/test/integration/campagnes/deleteCampagne.test.js, server/test/integration/campagnes/getAllCampagnes.test.js, server/test/integration/campagnes/getOneCampagne.test.js, server/test/integration/temoignages/createTemoignage.test.js, server/test/integration/utils/testUtils.js, server/yarn.lock
This PR migrate the mongodb driver to mongoose.
=> [Server] Mongoose migration

server/package.json, server/src/components.js, server/src/config.js, server/src/core/auth/strategies/jwtStrategy.js, server/src/core/auth/strategies/localStrategy.js, server/src/core/errors.js, server/src/core/http/httpServer.js, server/src/core/http/verifyUserMiddleware.js, server/src/core/users.js, server/src/core/utils/authenticateUtils.js, server/src/db/createUser.js, server/src/db/dbCli.js, server/src/models/user.js, server/src/users/usersHttp.js, server/src/users/validators.js, server/yarn.lock
Add authentication handling through JWT and refresh token.
Tests will be added later.
=> [Server] Add auth

server/src/middlewares/verifyUserMiddleware.js, server/src/models/user.model.js, server/src/routes/users.routes.js, server/src/utils/authenticate.utils.js, ui/src/App.js, ui/src/Components/Breadcrumbs.js, ui/src/ProtectedRoute.js, ui/src/campagnes/AddCampagne.js, ui/src/campagnes/AnswerCampagne.js, ui/src/campagnes/ViewCampagnes.js, ui/src/context/UserContext.js, ui/src/index.js, ui/src/routes.js, ui/src/users/Login.js, ui/src/utils/httpClient.js
This PR adds login handler in the UI and protects routes. It also leverage the reset token policy.
=> [UI - Server] Add auth

server/src/db/createUser.js, server/src/db/dbCli.js
This PR fixes broken import in create users CLI
=> [Server] broken import in create users cli

server/src/db/createUser.js
This PR fix the CLI for creating new users.
=> [Server] Fix create-user cli

ui/src/campagnes/AddCampagne.js, ui/src/campagnes/AnswerCampagne.js
This PR check the returned id in campagnes creation/answer instead of status.
=> [UI] Check returned id instead of status in campagnes

server/src/controllers/campagnes.controller.js, server/src/dao/campagnes.dao.js, server/src/routes/campagnes.routes.js, server/src/services/campagnes.service.js, server/test/integration/campagnes/updateCampagne.test.js, ui/package.json, ui/src/Components/Layout.js, ui/src/ProtectedRoute.js, ui/src/campagnes/AnswerCampagne.js, ui/src/campagnes/CampagneForm.js, ui/src/campagnes/EditCampagne.js, ui/src/campagnes/ViewCampagnes.js, ui/src/index.js, ui/src/routes.js, ui/src/utils/httpClient.js, ui/yarn.lock
This PR adds needed back-end and front-end to edit a campagne. It also adds a JSON visual editor.
=> [UI - server] Add campagnes edition

ui/src/Components/Form/CustomCheckboxes.js, ui/src/Components/Form/CustomRadios.js, ui/src/campagnes/AnswerCampagne.js, ui/src/campagnes/ViewCampagnes.js, ui/src/index.js
This PR adds the multistep form, enhance styles and add custom error handling in answer questionnaire.
=> [UI] Enhance temoignage

ui/package.json, ui/src/Components/Form/CustomTextarea.js, ui/src/Components/Layout.js, ui/src/Components/Stepper.js, ui/src/campagnes/AnswerCampagne.js, ui/src/index.js, ui/yarn.lock
=> [UI] Add form stepper

ui/src/Components/Form/CustomCheckboxes.js, ui/src/Components/Form/CustomRadios.js, ui/src/Components/Form/CustomText.js, ui/src/Components/Form/CustomTextarea.js, ui/src/Components/Stepper.js, ui/src/campagnes/AnswerCampagne.js
This PR adds a go back button, clickable previous category on stepper on a success message.
=> [UI] Enhance questionnaire

server/src/db/createUser.js, server/test/integration/users/getCurrentUser.test.js, server/test/integration/users/loginUser.test.js, server/test/integration/users/logoutUser.test.js, server/test/integration/users/refreshTokenUser.test.js, ui/src/users/Login.js
This PR fixes the case sensitivity issues in username.
=> [UI - server] Fix username case sensitivity

server/src/routes/campagnes.routes.js, server/test/integration/campagnes/createCampagne.test.js, server/test/integration/campagnes/deleteCampagne.test.js, server/test/integration/campagnes/getAllCampagnes.test.js, server/test/integration/campagnes/updateCampagne.test.js, server/test/integration/users/getCurrentUser.test.js, server/test/integration/users/logoutUser.test.js, server/test/integration/users/refreshTokenUser.test.js, server/test/integration/utils/user.js
This PR protect the campagnes routes
=> [Server] Protect campagnes routes

ui/src/campagnes/AnswerCampagne.js, ui/src/campagnes/CampagneForm.js, ui/src/campagnes/ViewCampagnes.js, ui/src/common/hooks/httpHooks.js, ui/src/utils/httpClient.js
Following the protection of campagne route this PR injects token in front-end request.
=> [UI] Inject token in request

ui/src/Components/Layout.js, ui/src/campagnes/ViewCampagnes.js, ui/src/temoignages/Components/TemoignagesModal.js, ui/src/temoignages/ViewTemoignages.js
This PR:
- widened the layout
- add tooltip on campagne name
- extract temoignage modal in own component
=> [UI] Enhance campagne and temoignage style

server/src/controllers/temoignages.controller.js, server/src/dao/temoignages.dao.js, server/src/routes/temoignages.routes.js, server/src/services/temoignages.service.js, server/src/validators/temoignages.validators.js, ui/src/campagnes/AnswerCampagne.js
Cette PR ajoute l'enregistrement des réponses du témoignage à chaque question.
=> [UI server] Save temoignage for each questions

server/src/dao/campagnes.dao.js, server/src/db/createUser.js, server/src/models/campagne.model.js, server/src/models/temoignage.model.js, server/test/dao/campagnes.dao.test.js, server/test/dao/temoignages.dao.test.js, server/test/integration/campagnes/createCampagne.test.js, server/test/integration/campagnes/getAllCampagnes.test.js, server/test/integration/campagnes/getOneCampagne.test.js, server/test/integration/temoignages/createTemoignage.test.js, server/test/integration/temoignages/getAllTemoignages.test.js, ui/src/campagnes/ViewCampagnes.js
Cette PR ajoute des timestamps de création et modifications sur les campagnes et témoignages. Ces timestamps sont ensuite affiché pour les campagnes dans le tableau correspondant.
=> [UI - Server] Add timestamps

ui/src/temoignages/Components/TemoignagesModal.js
This PR adds the scrollBehaviour props on temoignage modal.
=> [UI] Add scroll behaviour on modal

ui/src/temoignages/ViewTemoignages.js
This PR:
- reverse bar chart colors
- remove 0 from the bar chart
=> [UI] Enhance bar chart

ui/.eslintrc, ui/src/App.js, ui/src/Components/Footer.js, ui/src/Components/Form/Hero.js, ui/src/Components/Form/widgets/CustomMessageReceived.js, ui/src/Components/Form/widgets/CustomTextareaPrecision.js, ui/src/legal/CGU.js, ui/src/legal/MentionsInformation.js, ui/src/legal/PolitiqueConfidentialite.js
This PR adds:
- mentions d'information page
- CGU page
- Politique de confidentialité page
- Enable links to them in footer
- Add mentions d'informations popover and modal
=> [UI] Add legal mentions

server/src/controllers/temoignages.controller.js, server/src/errors.js, server/src/services/temoignages.service.js, server/test/fixtures.js, server/test/integration/temoignages/createTemoignage.test.js, server/test/services/temoignages.service.test.js, ui/src/Components/Form/Hero.js, ui/src/campagnes/AnswerCampagne.js, ui/src/campagnes/ViewCampagnes.js
This PR adds the handling of expired and not opened campagne.
=> [UI - server] Handle inactive campagne

ui/src/campagnes/CampagneForm.js, ui/src/campagnes/DuplicateCampagneModal.js, ui/src/campagnes/ViewCampagnes.js
This PR adds : 
- Search filter
- Move Link button at the start of table
- Enable duplication
=> [UI] Enhance ViewCampagne

reverse_proxy/Dockerfile, ui/package.json, ui/src/campagnes/CampagneExport.js, ui/src/campagnes/ExcelCampagneExport.js, ui/src/campagnes/ViewCampagnes.js, ui/src/index.js, ui/yarn.lock
Cette PR ajoute l'export des campagnes en XLSX et un zip des QR codes
=> [UI] Export des campagnes

ui/src/campagnes/CampagneExport.js, ui/src/campagnes/CampagneForm.js, ui/src/campagnes/LinkCampagneModal.js, ui/src/campagnes/ViewCampagnes.js, ui/src/temoignages/Components/EtablissementSelector.js, ui/src/users/Signup.js
Cette PR ajoute le champ `entreprise_raison_sociale` pour la sélection des etablissements
=> [UI] Ajout du champs`entreprise_raison_sociale`

server/src/controllers/users.controller.js, server/src/dao/users.dao.js, server/src/errors.js, server/src/models/user.model.js, server/src/routes/users.routes.js, server/src/services/users.service.js, server/src/validators/users.validators.js, ui/src/App.js, ui/src/users/Login.js, ui/src/users/Signup.js
Cette PR ajoute le endpoint nécessaire au fonctionnement de la page d'inscription ainsi que le formulaire accessible `/inscription`
=> [UI - server] Ajout page d'inscription

server/src/controllers/verbatims.controller.js, server/src/dao/campagnes.dao.js, server/src/dao/temoignages.dao.js, server/src/httpServer.js, server/src/routes/verbatims.routes.js, server/src/services/temoignages.service.js, server/src/services/verbatims.service.js, server/src/utils/verbatims.utils.js, ui/src/App.js, ui/src/Components/Navbar.js, ui/src/constants.js, ui/src/hooks/useFetchVerbatims.js, ui/src/hooks/useUpdateVerbatimStatus.js, ui/src/temoignages/Dashboard.js, ui/src/utils/httpClient.js, ui/src/verbatims/Moderation.js, ui/src/verbatims/ModerationTable.js
Cette PR ajoute le système de modération des verbatims
=> [ UI - server] Ajout modération des verbatims

server/src/utils/verbatims.utils.js
Cette PR corrige le bug de non affichage des noms d'établissement si inexistants dans le catalogue
=> [Server] Ajout des différents label d'établissement

ui/src/campagnes/Components/CellInput.js, ui/src/campagnes/Components/CellInputSeats.js
Cette PR ajoute aux cellules éditables :
- l'édition au double clic sur la cellule
- l'envoi en appuyant sur Entrée
- l'envoi au click à l'extérieur
=> [UI] Amélioration interaction cellules éditable

server/.eslintrc, server/package.json, server/src/config.js, server/src/controllers/users.controller.js, server/src/modules/slack.js, server/src/routes/users.routes.js, server/src/validators/users.validators.js, server/yarn.lock, ui/src/campagnes/Components/SupportModal.js, ui/src/campagnes/CreateCampagnes/Step1.js, ui/src/campagnes/ManageCampagnes.js
Cette PR envoi des notifications slack lorsqu'un utilisateur s'inscrit et lors d'une demande au support.
=> [UI - server] Ajout bot slack

server/src/validators/users.validators.js, ui/src/users/Components/EtablissementInput.js, ui/src/users/Signup.js
Etablissements field could be empty. I added a stronger validation and a small rework of the etablissement selection flow.
=> [UI - server] Fix signup issues

server/src/controllers/temoignages.controller.js, server/src/dao/temoignages.dao.ts, server/src/dao/types/temoignages.ts, server/src/dao/verbatims.dao.ts, server/src/modules/xlsxExport.js, server/src/routes/temoignages.routes.js, server/src/services/temoignages.service.js, server/src/utils/temoignages.utils.js, ui/src/campagnes/PreviewCampagnePage.js, ui/src/campagnes/ResultsCampagnesPage.js, ui/src/hooks/useFetchTemoignagesXlsExport.js, ui/src/queries/temoignages.js, ui/src/utils/httpClient.js
Ajoute un bouton pour extraire les témoignages et verbatims en XLSX.
=> [UI - server] Ajoute extract brut des témoignages

server/src/controllers/formations.controller.js, server/src/dao/formations.dao.ts, server/src/dao/verbatims.dao.ts, server/src/services/formations.service.js, server/src/services/verbatims.service.js, ui/src/hooks/useFetchLocalEtablissements.js, ui/src/hooks/useFetchLocalFormations.js, ui/src/queries/etablissements.js, ui/src/queries/formations.js, ui/src/verbatims/Moderation/ModerationEtablissementPicker.js, ui/src/verbatims/Moderation/ModerationFormationPicker.js, ui/src/verbatims/ModerationPage.js
Répare tout les soucis dans la recherche pour la modération
=> [UI -serveur] Répare la moderation

server/src/server.ts, ui/src/Components/DsfrFooter.js
=> feat: add version and appname

.talismanrc, ui/package.json, ui/src/campagnes/AnswerCampagnePage.js, ui/src/campagnes/CreateCampagnesPage.js, ui/src/campagnes/ManageCampagnesPage.js, ui/src/campagnes/PreviewCampagnePage.js, ui/src/campagnes/ResultsCampagnesPage.js, ui/src/guide/DiffusionGuidePage.js, ui/src/home/HomePage.js, ui/src/iframes/IframeEtablissementPage.js, ui/src/iframes/IframeFormationPage.js, ui/src/index.tsx, ui/src/legal/CguPage.js, ui/src/legal/MentionsInformationBackOfficePage.js, ui/src/legal/MentionsInformationQuestionnairePage.js, ui/src/questionnaires/Managing.js, ui/src/questionnaires/QuestionnaireForm.js, ui/src/statistics/StatisticsPage.js, ui/src/suivi/SuiviCampagnesPage.js, ui/src/suivi/SuiviEtablissementsPage.js, ui/src/temoignages/ManageTemoignagesPage.js, ui/src/users/EmailConfirmationPage.js, ui/src/users/LoginPage.js, ui/src/users/Managing.js, ui/src/users/PendingAccountPage.js, ui/src/users/SignupPage.js, ui/src/verbatims/ModerationPage.js, yarn.lock
Cette PR ajoute react-helmet-async et des titres à chaque page.
=> [UI] Ajoute des titres aux pages

ui/src/App.js, ui/src/users/Components/UsersTable/UsersTable.js
Cette PR ajoute Matomo et track lorsque:
- Env de prod
- Pas admin
- Pas désactivé le tracking à l'aide du param `notracking`
- Pas sudo
=> [UI] Ajoute matomo

.bin/scripts/run-playbook.sh
should fix the issue for desrypt logs
=> fix(debug): log file name

server/src/constants.ts, server/src/utils/temoignages.utils.ts
Cette PR réconcilie les valeurs de l'ancien et du nouveau questionnaire pour éviter les doublons.
=> [Serveur] Supprime les doublon dans iframe formation

.infra/files/configs/reverse_proxy/locations/90_location_ui.conf.template, ui/src/iframes/Components/TrouverUneEntrepriseRating.js, ui/src/iframes/IframeFormationPage.js, ui/src/matomo.js
Cette PR:
- Autorise tout les domaines de l'onisep dans les CSP
- Ajoute un champ height et src dans le postMessage
- Ajoute un customEvent manquant
=> [UI - infra] Prépare l'exposition de l'iframe sur l'Onisep
